package com.mycompany.myapp;

import CoVoiturage.entities.User;
import CoVoiturage.gui.CoVoiturageView;
import CoVoiturage.util.Db;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import java.util.Map;
import Colocation.gui.AddColocation;
import Colocation.gui.AffichCol;
import Colocation.gui.AffichageColoUSer;
import Colocation.gui.AjouterColocation;
import Colocation.gui.AjouterDemande;
import Colocation.gui.ColocationMenu;
import Objet.GUI.AffichObjPerd;
import Objet.GUI.AffichObjTrouv;
import com.codename1.ui.Container;
import com.codename1.ui.FontImage;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    Map h;
    private Form hi;
    private Resources theme;
    private Container mainContainer;
    public static Toolbar tb;
 

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        
       
        
        // Pro only feature
      //  Log.bindCrashProtection(true);
    }


    public void start() {
        if (hi != null) {
            hi.show();
            return;
        }
        hi = new Form("Hi World");
     
        tb = hi.getToolbar();
        
        User user = new User();
        user.setId(5);
        user.setUserName("amr");
        Db.getInstance().insertUser(user);
        
        tb.addMaterialCommandToSideMenu("Objets Perdus", FontImage.MATERIAL_HOME, e -> {AffichObjPerd a = new AffichObjPerd();
        
        });
        tb.addMaterialCommandToSideMenu("Objets Trouvés", FontImage.MATERIAL_WEB, e -> {  AffichObjTrouv a = new AffichObjTrouv();
        });
        tb.addMaterialCommandToSideMenu("CoVoiturage", FontImage.MATERIAL_WEB, e -> {  CoVoiturageView a = new CoVoiturageView();
        });
        tb.addMaterialCommandToSideMenu("CoLocation", FontImage.MATERIAL_WEB, e -> {  ColocationMenu a = new ColocationMenu();
        });
        hi.addComponent(new Label("Hi World"));
        hi.show();
    }

    public void stop() {
        hi = getCurrentForm();
        if (hi instanceof Dialog) {
            ((Dialog) hi).dispose();
            hi = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
